# Data Wrangling

## Descripción

Continuaremos hablando sobre lo trabajado en la práctica anterior... Crearás un notebook donde se desarrollará la limpieza de los datos elegidos para tu proyecto final, deberás tener en cuenta técnicas vistas en clase para el tratamiento de valores duplicados, nulos y outliers con su respectiva justificación.

### Consigna

* Iniciar el proceso de limpieza y exploración de datos.

* Explorar los tipos de las columnas y modificar según corresponda.

* Validar la presencia de valores perdidos y sugerir alguna solución.

* Validar la presencia de valores outliers y sugerir alguna solución.

### Aspectos a incluir

* Notebook con código y estructura eficiente.


### Ejemplo joya

* https://www.kaggle.com/code/mafaisal007/data-wrangling-tutorial

In [1]:
# Import data

import pandas as pd
import matplotlib.pyplot as plt

file_path = r'C:\Users\camil\OneDrive - Universidad Austral de Chile\datascience1\proyectoDS_parte1\Data_Science_ll\entrega_1\riqueza.csv'

In [2]:
df = pd.read_csv(file_path)
df.head()
#df.info()

,id,recording,site,year,month,day,hour,minute,species,songtype,x1,x2,y1,y2,frequency,validated,url,score,site_id,presencia
0,627470889,SMM09557_20231009_185000.wav,P04_SMM09557,2023,10,9,18,50,Theristicus melanopis,Common Song,19.210667,25.461333,796.875,2390.625,12000,present,https://rfcx-streams-production.s3.eu-west-1.a...,0.308460,48814,1
1,627471573,SMM09261_20231010_002000.wav,P02_SMM09261,2023,10,10,2,20,Theristicus melanopis,Common Song,20.330667,26.581333,796.875,2390.625,12000,(not validated),https://rfcx-streams-production.s3.eu-west-1.a...,0.315499,49108,0
2,627471783,SMM09261_20231008_051500.wav,P02_SMM09261,2023,10,8,7,15,Theristicus melanopis,Common Song,31.114667,37.365333,796.875,2390.625,12000,(not validated),https://rfcx-streams-production.s3.eu-west-1.a...,0.409870,49108,0
3,627472803,SMM09687_20231008_022500.wav,P.568_SMM09687,2023,10,8,2,25,Theristicus melanopis,Common Song,48.362667,54.613333,796.875,2390.625,12000,(not validated),https://rfcx-streams-production.s3.eu-west-1.a...,0.336434,48795,0
4,627472806,SMM09261_20231008_003500.wav,P02_SMM09261,2023,10,8,2,35,Theristicus melanopis,Common Song,24.704000,30.954667,796.875,2390.625,12000,(not validated),https://rfcx-streams-production.s3.eu-west-1.a...,0.439855,49108,0

## How to work with missing data
1. dentify misiing data
2. dela with missing data
3. correct data format

### there are tow methods to detect missing data:
1. .isnull()
2. notnull()

In [ ]:
# The output is a boolean value indicating whether the value that is passed into the argument is in fact missing data.

missing_data = df.isnull()
missing_data.head(5)

,id,recording,site,year,month,day,hour,minute,species,songtype,x1,x2,y1,y2,frequency,validated,url,score,site_id,presencia
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [6]:
# count the number of missing values in each column

for column in missing_data.columns.values.tolist():
    print(column)
    print(missing_data[column].value_counts())
    print("")

id
id
False    27224
Name: count, dtype: int64

recording
recording
False    27224
Name: count, dtype: int64

site
site
False    27224
Name: count, dtype: int64

year
year
False    27224
Name: count, dtype: int64

month
month
False    27224
Name: count, dtype: int64

day
day
False    27224
Name: count, dtype: int64

hour
hour
False    27224
Name: count, dtype: int64

minute
minute
False    27224
Name: count, dtype: int64

species
species
False    27224
Name: count, dtype: int64

songtype
songtype
False    27224
Name: count, dtype: int64

x1
x1
False    27224
Name: count, dtype: int64

x2
x2
False    27224
Name: count, dtype: int64

y1
y1
False    27224
Name: count, dtype: int64

y2
y2
False    27224
Name: count, dtype: int64

frequency
frequency
False    27224
Name: count, dtype: int64

validated
validated
False    27224
Name: count, dtype: int64

url
url
False    27224
Name: count, dtype: int64

score
score
False    27224
Name: count, dtype: int64

site_id
site_id
False    27224
Name: count, dtype: int64

presencia
presencia
False    27224
Name: count, dtype: int64

### Deal with missing data

**How to**

1. drop data
    * drop the whole row
    * drop the whole column

2. replace data
    * replace it by mean
    * replace it by frequency
    * replace it based on other functions

No se encontraron valores perdidos.

In [ ]:
# limpieza de columnas, y creación de columna datetime

file_path = r'C:\Users\camil\OneDrive - Universidad Austral de Chile\datascience1\proyectoDS_parte1\Data_Science_ll\entrega_1\riqueza.csv' #Cargar data limpia y sin NaN

df = pd.read_csv(file_path)
#df.head()
#df.info()

In [8]:
# crear columna datetime a partir de las columnas year, month, day, hour y minute

df['datetime'] = pd.to_datetime(df[['year', 'month', 'day', 'hour', 'minute']])
df.head()

,id,recording,site,year,month,day,hour,minute,species,songtype,...,x2,y1,y2,frequency,validated,url,score,site_id,presencia,datetime
0,627470889,SMM09557_20231009_185000.wav,P04_SMM09557,2023,10,9,18,50,Theristicus melanopis,Common Song,...,25.461333,796.875,2390.625,12000,present,https://rfcx-streams-production.s3.eu-west-1.a...,0.308460,48814,1,2023-10-09 18:50:00
1,627471573,SMM09261_20231010_002000.wav,P02_SMM09261,2023,10,10,2,20,Theristicus melanopis,Common Song,...,26.581333,796.875,2390.625,12000,(not validated),https://rfcx-streams-production.s3.eu-west-1.a...,0.315499,49108,0,2023-10-10 02:20:00
2,627471783,SMM09261_20231008_051500.wav,P02_SMM09261,2023,10,8,7,15,Theristicus melanopis,Common Song,...,37.365333,796.875,2390.625,12000,(not validated),https://rfcx-streams-production.s3.eu-west-1.a...,0.409870,49108,0,2023-10-08 07:15:00
3,627472803,SMM09687_20231008_022500.wav,P.568_SMM09687,2023,10,8,2,25,Theristicus melanopis,Common Song,...,54.613333,796.875,2390.625,12000,(not validated),https://rfcx-streams-production.s3.eu-west-1.a...,0.336434,48795,0,2023-10-08 02:25:00
4,627472806,SMM09261_20231008_003500.wav,P02_SMM09261,2023,10,8,2,35,Theristicus melanopis,Common Song,...,30.954667,796.875,2390.625,12000,(not validated),https://rfcx-streams-production.s3.eu-west-1.a...,0.439855,49108,0,2023-10-08 02:35:00

In [9]:
# eliminar columnas innecesarias
## las siguientes columnas no son necesarias para el análisis, ya que están fuera de los objetivos del proyecto.

df = df.drop(columns=['songtype', 'x1', 'x2', 'y1', 'y2'])
df.head()

,id,recording,site,year,month,day,hour,minute,species,frequency,validated,url,score,site_id,presencia,datetime
0,627470889,SMM09557_20231009_185000.wav,P04_SMM09557,2023,10,9,18,50,Theristicus melanopis,12000,present,https://rfcx-streams-production.s3.eu-west-1.a...,0.308460,48814,1,2023-10-09 18:50:00
1,627471573,SMM09261_20231010_002000.wav,P02_SMM09261,2023,10,10,2,20,Theristicus melanopis,12000,(not validated),https://rfcx-streams-production.s3.eu-west-1.a...,0.315499,49108,0,2023-10-10 02:20:00
2,627471783,SMM09261_20231008_051500.wav,P02_SMM09261,2023,10,8,7,15,Theristicus melanopis,12000,(not validated),https://rfcx-streams-production.s3.eu-west-1.a...,0.409870,49108,0,2023-10-08 07:15:00
3,627472803,SMM09687_20231008_022500.wav,P.568_SMM09687,2023,10,8,2,25,Theristicus melanopis,12000,(not validated),https://rfcx-streams-production.s3.eu-west-1.a...,0.336434,48795,0,2023-10-08 02:25:00
4,627472806,SMM09261_20231008_003500.wav,P02_SMM09261,2023,10,8,2,35,Theristicus melanopis,12000,(not validated),https://rfcx-streams-production.s3.eu-west-1.a...,0.439855,49108,0,2023-10-08 02:35:00

In [11]:
import sweetviz as sv

# Crear un reporte exploratorio con Sweetviz
reporte = sv.analyze(df)

# Guardar el reporte en un archivo HTML
reporte.show_html("reporte_exploratorio.html")

                                             |          | [  0%]   00:00 -> (? left)

Report reporte_exploratorio.html was generated! NOTEBOOK/COLAB USERS: the web browser MAY not pop up, regardless, the report IS saved in your notebook/colab files.

html reporte = 
file:///C:/Users/camil/OneDrive%20-%20Universidad%20Austral%20de%20Chile/datascience1/proyectoDS_parte1/Data_Science_ll/pre_entregas/reporte_exploratorio.html

**Insights**

* 27.224 registros
    * not present   12,165  45%
    * (not validated)   9,833   36%
    * present   5,226   19%

* 24 sitios
* 34 especies distintas
    1. Pygarrhichas albogularis
    2. Colaptes pitius
    3. Scelorchilus rubecola


* Score
    * MAX   0.956
    * MIN   0.200
    * AVG   0.351
    * MEDIAN    0.337

Los valores pueden existir en uno de tres estados; present, not present y (not validated).
Por lo tanto en los valores de 'species' estan considerados registros que no han sido validados por un revisor.

Se creará un df dejando fuera los registros en estado de (not validated) y se rehará el reporte exploratorio.

In [12]:
df_validated = df[df['validated'] != '(not validated)']
df_validated.head()

,id,recording,site,year,month,day,hour,minute,species,frequency,validated,url,score,site_id,presencia,datetime
0,627470889,SMM09557_20231009_185000.wav,P04_SMM09557,2023,10,9,18,50,Theristicus melanopis,12000,present,https://rfcx-streams-production.s3.eu-west-1.a...,0.308460,48814,1,2023-10-09 18:50:00
12,627488167,SMM09309_20231010_122000.wav,P39_SMM09309,2023,10,10,12,20,Theristicus melanopis,12000,not present,https://rfcx-streams-production.s3.eu-west-1.a...,0.319604,48993,0,2023-10-10 12:20:00
13,627488435,SMM09360_20231010_144000.wav,P23_SMM09360,2023,10,10,14,40,Theristicus melanopis,12000,not present,https://rfcx-streams-production.s3.eu-west-1.a...,0.320364,48816,0,2023-10-10 14:40:00
14,627488436,SMM09360_20231010_144500.wav,P23_SMM09360,2023,10,10,14,45,Theristicus melanopis,12000,not present,https://rfcx-streams-production.s3.eu-west-1.a...,0.347267,48816,0,2023-10-10 14:45:00
15,627488437,SMM09360_20231010_100500.wav,P23_SMM09360,2023,10,10,10,5,Theristicus melanopis,12000,present,https://rfcx-streams-production.s3.eu-west-1.a...,0.323306,48816,1,2023-10-10 10:05:00

In [13]:
import sweetviz as sv

# Crear un reporte exploratorio con Sweetviz
reporte = sv.analyze(df_validated)

# Guardar el reporte en un archivo HTML
reporte.show_html("reporte_exploratorio_validated.html")

                                             |          | [  0%]   00:00 -> (? left)

Report reporte_exploratorio_validated.html was generated! NOTEBOOK/COLAB USERS: the web browser MAY not pop up, regardless, the report IS saved in your notebook/colab files.

file:///C:/Users/camil/OneDrive%20-%20Universidad%20Austral%20de%20Chile/datascience1/proyectoDS_parte1/Data_Science_ll/pre_entregas/reporte_exploratorio_validated.html


**Insights**

* 17.391 registros
    * not present   12,165  70%
    * (not validated)   0   0%
    * present   5,226   30%



* 24 sitios
* 34 especies distintas
    1. Scelorchilus rubecula
    2. Sephanoides sephaniodes
    3. Curaeus curaeus


* Score
    * MAX   0.956
    * MIN   0.200
    * AVG   0.367
    * MEDIAN    0.350